version: "3"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DEBUG=true
    ports:
      - "8080:8080"
    tty: true